'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { GlassCard } from '@/components/ui/GlassCard';
import { Button } from '@/components/ui/Button';
import {
  BookOpenIcon,
  SparklesIcon,
  ChartBarIcon,
  ComputerDesktopIcon,
  CalculatorIcon,
  ClockIcon,
  BriefcaseIcon,
  BeakerIcon,
  TrophyIcon,
  DocumentMagnifyingGlassIcon,
} from '@heroicons/react/24/outline';

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0 },
};

export default function HomePage() {
  const features = [
    {
      icon: <BookOpenIcon className="w-6 h-6 text-primary-600" aria-hidden />,
      title: 'Interview Questions',
      description: 'Hand-picked questions from 40+ top tech companies, categorized by difficulty and rounds.',
      href: '/companies',
      color: 'blue'
    },
    {
      icon: <SparklesIcon className="w-6 h-6 text-purple-600" aria-hidden />,
      title: 'AI Roadmaps',
      description: 'Customized 4-week preparation plans generated by AI based on your specific target company.',
      href: '/roadmap',
      color: 'purple'
    },
    {
      icon: <DocumentMagnifyingGlassIcon className="w-6 h-6 text-amber-500" aria-hidden />,
      title: 'AI Resume Scorer',
      description: 'Get an instant ATS compatibility score and actionable feedback to land more interviews.',
      href: '/resume',
      color: 'gold'
    },
    {
      icon: <CalculatorIcon className="w-6 h-6 text-emerald-500" aria-hidden />,
      title: 'Advanced CGPA',
      description: 'Precise SGPA/CGPA calculations with target analysis to reach your academic goals.',
      href: '/cgpa-calculator',
      color: 'green'
    },
    {
      icon: <ClockIcon className="w-6 h-6 text-indigo-500" aria-hidden />,
      title: 'Spaced Repetition',
      description: 'Never forget a concept with our "Review Queue" using optimized scientific recall intervals.',
      href: '/spaced-repetition',
      color: 'indigo'
    },
    {
      icon: <ComputerDesktopIcon className="w-6 h-6 text-cyan-500" aria-hidden />,
      title: 'System Design',
      description: 'Master large-scale architectural design with interactive practice modules and roadmaps.',
      href: '/system-design',
      color: 'cyan'
    },
    {
      icon: <BriefcaseIcon className="w-6 h-6 text-rose-500" aria-hidden />,
      title: 'Job Tracker',
      description: 'Organize your applications through a powerful Kanban board to never miss a deadline.',
      href: '/applications',
      color: 'rose'
    },
    {
      icon: <BeakerIcon className="w-6 h-6 text-blue-500" aria-hidden />,
      title: 'Technical Quizzes',
      description: 'Test your knowledge on core CS fundamentals and language-specific timed assessments.',
      href: '/quiz',
      color: 'blue'
    },
    {
      icon: <TrophyIcon className="w-6 h-6 text-yellow-500" aria-hidden />,
      title: 'Leaderboard',
      description: 'Gamify your preparation and see where you stand among your peers in LNMIIT.',
      href: '/leaderboard',
      color: 'gold'
    },
  ];

  return (
    <div className="relative min-h-[calc(100vh-4rem)]">
      {/* Background Decor */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary-100/40 rounded-full blur-[120px]" />
        <div className="absolute bottom-[10%] right-[-5%] w-[35%] h-[35%] bg-accent-purple/20 rounded-full blur-[100px]" />
      </div>

      {/* Hero Section */}
      <section className="relative pt-24 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-container mx-auto text-center">
          <motion.div
            initial="hidden"
            animate="visible"
            variants={{ visible: { transition: { staggerChildren: 0.15 } } }}
          >
            <motion.div
              variants={fadeUp}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-gray-100 shadow-sm text-sm font-semibold text-primary-700 mb-8"
            >
              <span className="flex h-2 w-2 relative">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-primary-500"></span>
              </span>
              Built exclusively for LNMIIT Students
            </motion.div>

            <motion.h1
              variants={fadeUp}
              className="text-5xl sm:text-6xl md:text-7xl font-display font-black tracking-tight text-gray-900 mb-8"
            >
              Elevate Your <span className="bg-gradient-to-r from-primary-600 to-accent-purple bg-clip-text text-transparent">Placement</span> Journey.
            </motion.h1>

            <motion.p
              variants={fadeUp}
              className="text-xl md:text-2xl text-gray-600 mb-12 max-w-3xl mx-auto leading-relaxed"
            >
              The ultimate toolkit to master technical interviews, track your progress, and secure placements at dream companies with AI-driven insights.
            </motion.p>

            <motion.div variants={fadeUp} className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Link href="/companies">
                <Button variant="primary" size="lg" className="rounded-2xl px-10 py-5 text-lg shadow-xl shadow-primary-500/20">
                  Get Started for Free
                </Button>
              </Link>
              <Link href="/cgpa-calculator">
                <Button variant="secondary" size="lg" className="rounded-2xl px-10 py-5 text-lg hover:bg-gray-50">
                  Calculate CGPA
                </Button>
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Feature Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8 bg-gray-50/50">
        <div className="max-w-container mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-gray-900 mb-4 tracking-tight">Everything You Need, In One Place</h2>
            <p className="text-gray-500 max-w-2xl mx-auto text-lg">Integrated tools designed to handle every aspect of your placement preparation.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, idx) => (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: idx * 0.1, duration: 0.5 }}
              >
                <Link href={feature.href}>
                  <GlassCard className="h-full p-8 border-transparent hover:border-white hover:bg-white/80 transition-all duration-300 group cursor-pointer shadow-none hover:shadow-2xl hover:shadow-gray-200">
                    <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-6 transition-transform group-hover:scale-110
                      ${feature.color === 'blue' ? 'bg-blue-50 text-blue' :
                        feature.color === 'purple' ? 'bg-purple-50 text-purple-600' :
                          feature.color === 'gold' ? 'bg-amber-50 text-amber-600' :
                            feature.color === 'green' ? 'bg-emerald-50 text-emerald-600' :
                              feature.color === 'indigo' ? 'bg-indigo-50 text-indigo-600' :
                                feature.color === 'rose' ? 'bg-rose-50 text-rose-600' :
                                  feature.color === 'cyan' ? 'bg-cyan-50 text-cyan-600' : 'bg-gray-100'}
                    `}>
                      {feature.icon}
                    </div>
                    <h3 className="text-xl font-display font-bold text-gray-900 mb-3 group-hover:text-primary-600 transition-colors">
                      {feature.title}
                    </h3>
                    <p className="text-gray-600 leading-relaxed text-base font-normal">
                      {feature.description}
                    </p>
                  </GlassCard>
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-24 px-4 sm:px-6 lg:px-8">
        <div className="max-w-5xl mx-auto">
          <GlassCard className="bg-gradient-to-r from-primary-600 to-accent-purple p-12 md:p-16 text-center border-none shadow-2xl shadow-primary-500/30 overflow-hidden relative" glowColor="none" hoverEffect={false}>
            <div className="absolute inset-0 bg-mesh opacity-20 pointer-events-none" />
            <div className="relative z-10">
              <h2 className="text-3xl md:text-5xl font-display font-bold text-white mb-6">Built for LNMIITians. Free Forever.</h2>
              <p className="text-white/80 text-lg md:text-xl mb-10 max-w-2xl mx-auto">
                Join hundreds of your batchmates already using Selection Intel to crack top companies.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link href="/auth/signup">
                  <Button className="bg-white text-primary-600 hover:bg-gray-50 border-none rounded-2xl px-12 py-6 text-lg font-bold shadow-lg">
                    Create Account
                  </Button>
                </Link>
                <Link href="/companies">
                  <Button variant="secondary" className="border-white/30 text-white hover:bg-white/10 rounded-2xl px-12 py-6 text-lg font-bold">
                    Start Prep
                  </Button>
                </Link>
              </div>
            </div>
          </GlassCard>
        </div>
      </section>
    </div>
  );
}

