import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase credentials');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function seed() {
    console.log('Checking question count...');
    const { count } = await supabase.from('questions').select('*', { count: 'exact', head: true });
    console.log(`Current questions count: ${count}`);

    console.log('Looking for Google company ID...');
    const { data: company, error: companyError } = await supabase
        .from('companies')
        .select('id')
        .eq('slug', 'google')
        .single();

    if (companyError || !company) {
        console.error('Could not find Google in companies table.', companyError);
        return;
    }

    console.log(`Found Google ID: ${company.id}. Checking for existing questions...`);
    const { data: existingQ } = await supabase
        .from('questions')
        .select('id')
        .eq('company_id', company.id)
        .limit(1);

    if (!existingQ || existingQ.length === 0) {
        console.log('No questions found for Google. Seeding Two Sum...');

        // Also ensuring required columns match the table schema which usually includes id generated by default
        const { data: inserted, error: insertError } = await supabase
            .from('questions')
            .insert({
                company_id: company.id,
                round: 'Technical 1',
                question: 'Two Sum',
                topic: 'Arrays',
                difficulty: 'Easy',
                frequency: 100,
                year_reported: 2026,
                is_approved: true,
                source_url: 'https://leetcode.com/problems/two-sum'
            })
            .select();

        if (insertError) {
            console.error('Failed to seed question:', insertError);
        } else {
            console.log('Successfully seeded question:', inserted);
        }
    } else {
        console.log('Questions already exist for Google, skipping seed.');
    }
}

seed().catch(console.error);
